apiVersion: apps/v1 
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: {{.Values.replicas}}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.1 # This is my image
        name: guestbook-ui
        ports:
        - containerPort: 80
